# LocalStack
#localStackApiEndpoint = "http://localhost:5000/download"
localStackApiEndpoint = "https://api.localstack.cloud/download"


# Meta Data for SEO

## Homepage
title = "LocalStack"
logo = "/images/header-logo.svg"
titleSeparator = "-"
titleAddition = "A fully functional local cloud stack"
description = "Develop and test your cloud apps offline"

## Open Graph + Twitter Cards
images = ["/images/localstack.png", "/images/header-logo.svg"]
twitterSite = "_localstack"
twitterCreator = "_localstack"
#facebookAuthor = "localstack"
#facebookPublisher = "localstack"
ogLocale = "en_US"

## JSON-LD
schemaType = "Organization"
schemaLogo = "/images/localstack.png"
schemaTwitter = "https://twitter.com/_localstack"
schemaLinkedIn = "https://www.linkedin.com/"
schemaGitHub = "https://github.com/localstack"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"

# Alert
alert = false
alertText = "Like Doks? <a class=\"alert-link\" href=\"https://github.com/h-enk/doks/stargazers\">Star on GitHub</a>. Thanks!</a>"

# Edit Page
docsRepo = "https://github.com/localstack/localstack.github.io"
editPage = false

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = true
  darkMode = false
  bootStrapJs = true
  breadCrumb = false
  highLight = true
  kaTex = false
